apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpine-disk
  namespace: alpine-dr
  labels:
    drapp: alpine-app
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: alpine-source
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Block
