apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: alpine-storage-migration
spec:
  updateVolumesStrategy: Migration
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        name: src-disk
      spec:
        source:
          registry:
            url: 'docker://quay.io/kubevirt/alpine-container-disk-demo:20241126_959eee0dfd'
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: gp3-csi
          volumeMode: Block
  running: true
  template:
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 128Mi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 10
      volumes:
        - dataVolume:
            name: src-disk
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: alpine
              user: alpine              
          name: cloudinitdisk
